### ISSUE TITLE
malformed VCF header

### ISSUE THREAD

**Issue by mparker2** [schneebergerlab/msyd#11]
Hi both,

I'm having fun using msyd :) Just fyi: there is a quotation mark missing from the ALT=<ID=CROSSSYN> line in the VCF header output of msyd that leads to some issues when trying to load VCFs in IGV

https://github.com/schneebergerlab/msyd/blob/7fb9d538f02eea834e15b3bfe9d868880158d4db/msyd/pyxfiles/io.pyx#L388

Easy to fix :)

Matt

**Comment by lrauschning** [comment]
Nice that you're having fun :D

Thanks for noticing, will push a fix!
