### ISSUE TITLE
Feature request: print table of pansyn regions when running pansyri from command line

### ISSUE THREAD

**Issue by mnshgl0110** [schneebergerlab/msyd#7]
I think it would be nicer if pansyri could print the pansynetic regions. I guess the output could be in the following format:
```
$pansyri -i genomes.tsv --sp --syn
pansyn_region_1 Genome1:Chr1:start-end   Genome2:Chr1:start-end  Genome3:Chr1:start-end
pansyn_region_2 Genome1:Chr2:start-end   Genome2:Chr2:start-end  Genome3:Chr2:start-end
```
In the end we would need to fit the output in the VCF but for now something like this would be more useful than outputting pansyn object that are not readable from the command line.

**Comment by lrauschning** [comment]
Closing this, as `-p` will do this.
